// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aneyhilsmngwrbublskk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZXloaWxzbW5nd3JidWJsc2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2ODIwOTEsImV4cCI6MjA0OTI1ODA5MX0.L5ScCKsuRLACURmFtiJ-48PLaSjYlGOyd4zuK6AFwgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);